import type { Lead } from "@/modules/leads/types";

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    companyId: "company-dls",
    contactId: "contact-001",
    source: "website_quote",
    title: "Ampliacion de bodega con estructura metalica",
    serviceInterest: "Fabricacion de estructuras metalicas",
    projectLocation: "Quilicura, Santiago",
    urgency: "high",
    status: "qualified",
    notes: "Cliente cuenta con medidas preliminares y requiere visita tecnica.",
    createdAt: "2026-06-20T09:35:00.000Z",
    updatedAt: "2026-06-23T12:05:00.000Z",
    createdBy: "system",
    updatedBy: "sales-demo",
    deletedAt: null,
    metadata: {
      form: "quote",
      estimatedAreaM2: 180,
    },
  },
  {
    id: "lead-002",
    companyId: "company-dls",
    contactId: "contact-002",
    source: "whatsapp",
    title: "Reparacion de piezas con soldadura industrial",
    serviceInterest: "Soldadura industrial",
    projectLocation: "Los Andes",
    urgency: "medium",
    status: "contacted",
    notes: "Enviar rango estimado y pedir fotos de las piezas.",
    createdAt: "2026-06-21T14:18:00.000Z",
    updatedAt: "2026-06-23T16:50:00.000Z",
    createdBy: "system",
    updatedBy: "sales-demo",
    deletedAt: null,
    metadata: {
      channel: "whatsapp",
      hasPhotos: false,
    },
  },
  {
    id: "lead-003",
    companyId: "company-dls",
    contactId: "contact-003",
    source: "website_contact",
    title: "Montaje estructural para zona de carga",
    serviceInterest: "Montaje estructural",
    projectLocation: "Talcahuano",
    urgency: "planning",
    status: "new",
    notes: "Pendiente primer contacto telefonico.",
    createdAt: "2026-06-22T10:05:00.000Z",
    updatedAt: "2026-06-22T10:05:00.000Z",
    createdBy: "system",
    updatedBy: "system",
    deletedAt: null,
    metadata: {
      form: "contact",
      preferredSchedule: "manana",
    },
  },
];
