import type { Contact } from "@/modules/contacts/types";

export const mockContacts: Contact[] = [
  {
    id: "contact-001",
    companyId: "company-dls",
    type: "company",
    name: "Marcela Rivas",
    companyName: "Constructora Norte SpA",
    email: "marcela.rivas@example.cl",
    phone: "+56 9 1111 2222",
    preferredChannel: "email",
    source: "website_quote",
    notes: "Solicito estructura metalica para ampliacion de bodega.",
    status: "active",
    createdAt: "2026-06-20T09:30:00.000Z",
    updatedAt: "2026-06-23T12:00:00.000Z",
    createdBy: "system",
    updatedBy: "system",
    deletedAt: null,
    metadata: {
      industry: "construccion",
      region: "Metropolitana",
    },
  },
  {
    id: "contact-002",
    companyId: "company-dls",
    type: "person",
    name: "Jorge Fuentes",
    companyName: "Taller Industrial Los Andes",
    email: "jorge.fuentes@example.cl",
    phone: "+56 9 3333 4444",
    preferredChannel: "whatsapp",
    source: "whatsapp",
    notes: "Requiere reparacion y refuerzo de piezas soldadas.",
    status: "active",
    createdAt: "2026-06-21T14:15:00.000Z",
    updatedAt: "2026-06-23T16:45:00.000Z",
    createdBy: "system",
    updatedBy: "system",
    deletedAt: null,
    metadata: {
      industry: "metalurgia",
      region: "Valparaiso",
    },
  },
  {
    id: "contact-003",
    companyId: "company-dls",
    type: "company",
    name: "Camila Torres",
    companyName: "Logistica Sur",
    email: "camila.torres@example.cl",
    phone: "+56 9 5555 6666",
    preferredChannel: "phone",
    source: "website_contact",
    notes: "Busca montaje estructural para zona de carga.",
    status: "active",
    createdAt: "2026-06-22T10:00:00.000Z",
    updatedAt: "2026-06-22T10:00:00.000Z",
    createdBy: "system",
    updatedBy: "system",
    deletedAt: null,
    metadata: {
      industry: "logistica",
      region: "Biobio",
    },
  },
];
